name: TextingTheory Bot

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.43.1-focal

    env:
      REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
      REDDIT_SECRET: ${{ secrets.REDDIT_SECRET }}
      REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
      REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      GEMINI_API_KEY_ALT: ${{ secrets.GEMINI_API_KEY_ALT }}
      GEMINI_API_KEY_ALT_2: ${{ secrets.GEMINI_API_KEY_ALT_2 }}
      IMGUR_CLIENT_ID: ${{ secrets.IMGUR_CLIENT_ID }}
      PROMPT_KEY: ${{ secrets.PROMPT_KEY }}
      POST_ID: ${{ github.event.client_payload.post_id }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
    
      - name: Set up virtualenv and install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
    
      - name: Restore Reddit session
        run: |
          echo "${{ secrets.REDDIT_STORAGE_B64 }}" | base64 -d > reddit_storage.json

      - name: Run the bot
        run: |
          source .venv/bin/activate
          xvfb-run -a python main.py
