name: TextingTheory Bot

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    env:
      REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
      REDDIT_SECRET: ${{ secrets.REDDIT_SECRET }}
      REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
      REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      IMGUR_CLIENT_ID: ${{ secrets.IMGUR_CLIENT_ID }}
      PROMPT_KEY: ${{ secrets.PROMPT_KEY }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      KV_NAMESPACE_ID: ${{ secrets.KV_NAMESPACE_ID }}
      POST_ID: ${{ github.event.client_payload.post_id }}
      ANNOTATE_COMMENTS: ${{ toJson(github.event.client_payload.comments) }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
    
      - name: Cache virtual environment
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            venv-${{ runner.os }}-
    
      - name: Set up virtualenv and install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
    
      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
            path: ~/.cache/ms-playwright
            key: ${{ runner.os }}-playwright-${{ hashFiles('**/requirements.txt') }}
            restore-keys: |
              ${{ runner.os }}-playwright-
    
      - name: Install Playwright Browsers
        run: |
          source .venv/bin/activate
          playwright install

      - name: Install system dependencies for Playwright
        run: |
          for i in {1..2}; do sudo timeout 30 apt-get update && break || sleep 10; done
          sudo apt-get install -y \
            libnss3 \
            libatk-bridge2.0-0 \
            libgtk-3-0 \
            libxss1 \
            libx11-xcb1 \
            libgbm1 \
            libasound2t64 \
            xvfb
    
      - name: Restore Reddit session
        run: |
          echo "${{ secrets.REDDIT_STORAGE_B64 }}" | base64 -d > reddit_storage.json

      - name: Run the bot
        run: |
          source .venv/bin/activate
          xvfb-run -a python main.py
